server:
  port: 2000

jwt:
  secret: "MySuperSecureSecretKeyForJwtSignatures123!"
  expiration-ms: 86400000

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8765/eureka/

spring:
  application:
    name: gateway
  main:
    web-application-type: reactive
  cloud:
    config:
      enabled: false
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: true
          routes:
            - id: user
              uri: lb://user
              predicates:
                - Path=/api/v1/user/**
              filters:
                - StripPrefix=3
            - id: authentication
              uri: lb://authentication
              predicates:
                - Path=/api/v1/auth/**
              filters:
                - StripPrefix=3

management:
  endpoints:
    web:
      exposure:
        include: "*"
#  endpoint:
#    gateway:
#      enabled: true
